# Setup
name: arumlee.github.io
description: arumlee 기술블로그
tagline: A responsive theme for your project on GitHub Pages
baseurl: ""
locale: "ko"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
